
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 05 20:53:18 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 13;
  public static final int CONST = 28;
  public static final int NUMCONST = 3;
  public static final int LPAREN = 9;
  public static final int SEMI = 20;
  public static final int CONTINUE = 24;
  public static final int MINUS = 30;
  public static final int RPAREN = 10;
  public static final int GRE = 39;
  public static final int AND = 45;
  public static final int LS = 40;
  public static final int OR = 29;
  public static final int COMMA = 11;
  public static final int CLASS = 19;
  public static final int LSE = 41;
  public static final int DIV = 34;
  public static final int PLUS = 31;
  public static final int IF = 21;
  public static final int DOT = 15;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int RBRACKET = 14;
  public static final int EQUAL = 27;
  public static final int NEW = 32;
  public static final int error = 1;
  public static final int PPLUS = 16;
  public static final int MUL = 33;
  public static final int NEQ = 37;
  public static final int BREAK = 23;
  public static final int IDENT = 2;
  public static final int VOID = 44;
  public static final int EQ = 36;
  public static final int LBRACE = 7;
  public static final int ELSE = 22;
  public static final int READ = 43;
  public static final int CHARCONST = 5;
  public static final int WHILE = 18;
  public static final int RBRACE = 8;
  public static final int BOOLCONST = 4;
  public static final int EXTENDS = 12;
  public static final int PROG = 6;
  public static final int PROC = 35;
  public static final int GR = 38;
  public static final int DO = 42;
  public static final int PRINT = 26;
  public static final int MMINUS = 17;
}

